import { copy, type LocalizedText } from "./translations";
export type Service = {
    slug: string;
    title: LocalizedText;
    authority: LocalizedText;
    category: string;
    description: LocalizedText;
    eligibility: LocalizedText[];
    documents: LocalizedText[];
    fees: {
        type: LocalizedText;
        amount: LocalizedText;
        timeline: LocalizedText;
    }[];
    processSteps: LocalizedText[];
    relatedServices: LocalizedText[];
};
export const services: Service[] = [
    { slug: 'new-passport', title: copy.newPassportApplication, authority: copy.directorateGeneralOfImmigrationPassports, category: 'Passport', description: copy.aClearGuideToApplyingForYourFirstPakistani, eligibility: [copy.pakistaniCitizenWithAValidCnicOrBform, copy.applicantMustAppearInPersonForBiometricCapture, copy.minorsMustBeAccompaniedByAParentOrLegal], documents: [copy.originalCnicBform, copy.twoRecentPassportPhotographs, copy.proofOfAddress, copy.parentCnicForApplicantsUnder18], fees: [{ type: copy.normal, amount: copy.feeAmount4, timeline: copy.value10WorkingDays }, { type: copy.urgent, amount: copy.feeAmount5, timeline: copy.value4WorkingDays }, { type: copy.fastTrack, amount: copy.feeAmount6, timeline: copy.value2WorkingDays }], processSteps: [copy.confirmEligibilityAndPrepareYourDocuments, copy.chooseAPassportOfficeAndApplicationCategory, copy.visitTheOfficeForTokenAndBiometricCapture, copy.reviewAndSubmitYourApplicationDetails, copy.collectYourPassportAfterTheStatedTimeline], relatedServices: [copy.passportRenewal, copy.cnicRenewal] },
    { slug: 'passport-renewal', title: copy.passportRenewal, authority: copy.directorateGeneralOfImmigrationPassports, category: 'Passport', description: copy.renewAnExpiredOrExpiringPassportWithAPractical, eligibility: [copy.existingPakistaniPassportHolder, copy.passportIsExpiredOrHasLessThan6Months, copy.applicantAppearsInPersonForVerification], documents: [copy.originalCnic, copy.previousPassport, copy.recentPhotograph, copy.proofOfAddress], fees: [{ type: copy.normal, amount: copy.feeAmount4, timeline: copy.value10WorkingDays }, { type: copy.urgent, amount: copy.feeAmount5, timeline: copy.value4WorkingDays }, { type: copy.fastTrack, amount: copy.feeAmount6, timeline: copy.value2WorkingDays }], processSteps: [copy.checkYourPassportExpiryAndDocumentValidity, copy.selectNormalUrgentOrFasttrackProcessing, copy.visitTheSelectedPassportOffice, copy.completeBiometricVerificationAndReviewDetails, copy.trackAndCollectYourRenewedPassport], relatedServices: [copy.newPassportApplication, copy.cnicRenewal] },
    { slug: 'learner-driving-permit', title: copy.learnersDrivingPermit, authority: copy.trafficPoliceLicensingAuthority, category: 'Driving License', description: copy.understandTheAgeDocumentsAndTestRequirementsForA, eligibility: [copy.applicantMeetsTheMinimumAgeForTheVehicleClass, copy.validCnicOrJuvenileRegistrationCertificate, copy.medicalFitnessWhereRequired], documents: [copy.originalCnic, copy.medicalCertificate, copy.recentPassportPhotographs, copy.feeChallan], fees: [{ type: copy.learnerPermit, amount: copy.feeAmount7, timeline: copy.sameDay }, { type: copy.renewal, amount: copy.feeAmount8, timeline: copy.sameDay }, { type: copy.testFee, amount: copy.varies, timeline: copy.onAppointment }], processSteps: [copy.checkYourProvincespecificAgeRequirement, copy.prepareCnicPhotographsAndMedicalCertificate, copy.submitTheFormAndPayTheChallan, copy.takeTheLearnerTestIfApplicable, copy.receiveYourLearnerPermitAndNoteItsExpiry], relatedServices: [copy.cnicRegistration, copy.biometricVehicleTransfer] },
    { slug: 'cnic-registration', title: copy.cnicRegistration, authority: copy.nadra, category: 'CNIC/NADRA', description: copy.aStructuredGuideForFirsttimeCnicRegistrationWithNadra, eligibility: [copy.pakistaniCitizenAged18OrAbove, copy.applicantAppearsWithABloodRelativeOrVerifierWhere, copy.noExistingCnicRecord], documents: [copy.bformOrBirthCertificate, copy.parentOrBloodRelativeCnic, copy.proofOfResidence, copy.recentPhotograph], fees: [{ type: copy.normal, amount: copy.feeAmount12, timeline: copy.value31Days }, { type: copy.urgent, amount: copy.feeAmount13, timeline: copy.value23Days }, { type: copy.executive, amount: copy.feeAmount14, timeline: copy.value9Days }], processSteps: [copy.gatherIdentityAndFamilyVerificationDocuments, copy.visitANadraRegistrationCentre, copy.provideFingerprintsPhotoAndSignature, copy.reviewThePrintedFormCarefully, copy.collectYourCnicThroughTheSelectedDeliveryMethod], relatedServices: [copy.cnicRenewal, copy.newPassportApplication] },
    { slug: 'cnic-renewal', title: copy.cnicRenewal, authority: copy.nadra, category: 'CNIC/NADRA', description: copy.renewYourCnicBeforeOrAfterExpiryAndUnderstand, eligibility: [copy.existingCnicHolder, copy.cnicIsExpiredOrExpiringSoon, copy.applicantCanCompleteBiometricVerification], documents: [copy.originalCnic, copy.proofOfAddressIfDetailsChanged, copy.recentPhotograph, copy.supportingDocumentsForAnyUpdate], fees: [{ type: copy.normal, amount: copy.feeAmount12, timeline: copy.value31Days }, { type: copy.urgent, amount: copy.feeAmount13, timeline: copy.value23Days }, { type: copy.executive, amount: copy.feeAmount14, timeline: copy.value9Days }], processSteps: [copy.reviewWhetherYourPersonalDetailsNeedUpdating, copy.chooseANadraCentreOrPakIdentityRoute, copy.completeBiometricVerification, copy.verifyTheApplicationFormAndPayAnyApplicableFee, copy.trackDeliveryOrCollectFromTheCentre], relatedServices: [copy.cnicRegistration, copy.passportRenewal] },
    { slug: 'vehicle-transfer', title: copy.biometricVehicleTransfer, authority: copy.exciseTaxationDepartment, category: 'Vehicle Registration', description: copy.transferVehicleOwnershipWithTheRequiredBiometricVerificationAnd, eligibility: [copy.buyerAndSellerHaveValidIdentityDocuments, copy.vehicleTaxAndRegistrationRecordIsClear, copy.bothPartiesCanCompleteBiometricVerification], documents: [copy.originalRegistrationBookcard, copy.buyerAndSellerCnics, copy.saleAgreement, copy.tokenTaxPaymentProof], fees: [{ type: copy.transferFee, amount: copy.variesByEngine, timeline: copy.sameDay }, { type: copy.biometric, amount: copy.feeAmount15, timeline: copy.sameDay }, { type: copy.smartCard, amount: copy.feeAmount16, timeline: copy.value714Days }], processSteps: [copy.verifyVehicleRecordAndOutstandingTokenTax, copy.prepareBuyerSellerAndVehicleDocuments, copy.completeBiometricVerificationForBothParties, copy.submitTransferApplicationAtTheExciseOffice, copy.collectTheUpdatedRegistrationCard], relatedServices: [copy.learnerPermitRelated, copy.cnicRenewal] },
    { slug: 'fbr-income-tax', title: copy.fbrIncomeTaxFiling, authority: copy.federalBoardOfRevenue, category: 'Tax & Revenue', description: copy.prepareForIncomeTaxFilingWithAPlainlanguageList, eligibility: [copy.individualWithTaxableIncomeOrFilingObligation, copy.validCnicAndActiveIrisAccount, copy.incomeAndExpenseRecordsAvailable], documents: [copy.cnic, copy.salaryCertificateOrIncomeRecords, copy.bankAndInvestmentStatements, copy.propertyOrVehicleRecordsWhereApplicable], fees: [{ type: copy.filing, amount: copy.noGovernmentFee, timeline: copy.withinTaxYear }, { type: copy.professionalHelp, amount: copy.varies, timeline: copy.byAgreement }, { type: copy.lateFiling, amount: copy.penaltyMayApply, timeline: copy.afterDeadline }], processSteps: [copy.collectIncomeTaxDeductionAndExpenseRecords, copy.confirmYourFilingYearAndTaxpayerProfile, copy.enterInformationInTheOfficialIrisPortal, copy.reviewTaxCalculationAndSubmitReturn, copy.saveTheAcknowledgementForYourRecords], relatedServices: [copy.cnicRenewal, copy.vehicleTransferRelated] },
    { slug: 'domicile-certificate', title: copy.domicileCertificate, authority: copy.provincialAdministrationDeputyCommissionerOffice, category: 'Documents', description: copy.understandTheEvidenceUsedToEstablishAPermanentPlace, eligibility: [copy.permanentResidentOfTheRelevantDistrict, copy.applicantMeetsProvincespecificResidenceRules, copy.noConflictingDomicileRecord], documents: [copy.cnicOrBform, copy.proofOfResidence, copy.parentOrGuardianDomicileWhereRequired, copy.affidavitAndPhotographs], fees: [{ type: copy.application, amount: copy.feeAmount17, timeline: copy.value37WorkingDays }, { type: copy.urgent, amount: copy.varies, timeline: copy.byDistrict }, { type: copy.affidavit, amount: copy.varies, timeline: copy.sameDay }], processSteps: [copy.confirmDistrictAndApplicationOffice, copy.collectResidenceAndIdentityEvidence, copy.submitFormWithAffidavitAndPhotographs, copy.respondToAnyVerificationRequest, copy.collectTheSignedCertificate], relatedServices: [copy.policeCharacterCertificate, copy.cnicRegistration] },
    { slug: 'character-certificate', title: copy.policeCharacterCertificate, authority: copy.policeKhidmatMarkazDistrictPolice, category: 'Documents', description: copy.prepareTheDocumentsNeededForAPoliceCharacterOr, eligibility: [copy.applicantHasAValidIdentityDocument, copy.applicantCanProvideCurrentAndPreviousAddressDetails, copy.purposeOfCertificateIsStatedClearly], documents: [copy.cnicOrPassport, copy.proofOfCurrentAddress, copy.passportPhotographs, copy.letterFromEmployerOrInstitutionIfRequested], fees: [{ type: copy.standard, amount: copy.feeAmount18, timeline: copy.value37WorkingDays }, { type: copy.urgent, amount: copy.varies, timeline: copy.value12WorkingDays }, { type: copy.verification, amount: copy.included, timeline: copy.duringProcessing }], processSteps: [copy.selectYourLocalPoliceServiceCentre, copy.completeTheApplicationWithAddressHistory, copy.submitIdentityDocumentsAndPhotographs, copy.attendVerificationIfRequested, copy.collectTheCertificateOrUseTheStatedDeliveryOption], relatedServices: [copy.domicileCertificate, copy.passportRenewal] }
];
export const getService = (slug: string) => services.find(service => service.slug === slug);
export const categories = ['Passport', 'CNIC/NADRA', 'Driving License', 'Vehicle Registration', 'Tax & Revenue', 'Documents'];
export const categoryLabels: Record<string, LocalizedText> = Object.fromEntries([copy.passport, copy.cnicnadra, copy.drivingLicense, copy.vehicleRegistration, copy.taxRevenue, copy.documents].map(label => [label.en, label]));
